experiment: neac_walker
algo: neac
env_name: BipedalWalker-v2
base_seed: 42

training_steps: 5000000
gamma: 0.99
nsteps: 60
beta_entropy: 0.001
lr: 0.001

dnd:
  size: 5000
  lr: 0.5 
  key_size: 64
  use_critic_grads: True

log_frequency: 100  # episodes
val_frequency: 25000  # steps
val_episodes: 100
