hyperopt:
  lr: ["uniform", [0.0001, 0.01]]
  gamma: ["uniform", [0.95, 0.99]]
  nsteps: ["choice", [10, 20, 30, 40, 50, 60, 70]]
  beta_entropy: ["uniform", [0.0001, 0.1]]
  hidden_size: ["choice", [24, 32, 64, 128]]